version: '3.9'
services: 
  django:
    image: buysell:1.0
    ports:
      - 8000:8000
    env_file:
      - ./.DJANGO_SECRET_KEY
    volumes:
      - sqlyte:/home/django/mysite/
volumes:
  sqlyte:
    driver: local