# Generated by Django 4.0 on 2022-08-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_orderdetail_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='checkout_session_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
